# Generated by Django 2.0.2 on 2020-04-17 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hands_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_name', models.CharField(default='No information', max_length=64)),
                ('hand_detail', models.TextField(default='No info available', max_length=256)),
                ('hand_contact', models.IntegerField()),
                ('hand_rate_per_day', models.IntegerField(default=20)),
                ('hand_skill', models.CharField(default='Others', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
