# Generated by Django 2.0.2 on 2020-04-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0002_auto_20200417_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hands_info',
            old_name='hand_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='hands_info',
            old_name='hand_detail',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hands_info',
            old_name='hand_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hands_info',
            old_name='hand_rate_per_day',
            new_name='rate_per_day',
        ),
        migrations.RenameField(
            model_name='hands_info',
            old_name='hand_skill',
            new_name='skills',
        ),
    ]
