# Generated by Django 2.0.2 on 2020-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0003_auto_20200417_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='hands_info',
            name='portrait',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
