# Generated by Django 2.0.2 on 2020-04-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200419_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_detail',
            name='taken',
        ),
    ]
