# Generated by Django 2.0.2 on 2020-04-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_job_detail_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='position',
            field=models.CharField(max_length=32),
        ),
    ]
